/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FIRRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "firCount"
      | "getFIR"
      | "getVerification"
      | "isFIRRegistered"
      | "registerFIR"
      | "verifyFIR"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FIRCreated" | "FIRVerified"): EventFragment;

  encodeFunctionData(functionFragment: "firCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "getFIR", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getVerification",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isFIRRegistered",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerFIR",
    values: [string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "verifyFIR", values: [string]): string;

  decodeFunctionResult(functionFragment: "firCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFIR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFIRRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerFIR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyFIR", data: BytesLike): Result;
}

export namespace FIRCreatedEvent {
  export type InputTuple = [
    firId: string,
    cid: string,
    dataHash: string,
    timestamp: BigNumberish,
    registeredBy: AddressLike
  ];
  export type OutputTuple = [
    firId: string,
    cid: string,
    dataHash: string,
    timestamp: bigint,
    registeredBy: string
  ];
  export interface OutputObject {
    firId: string;
    cid: string;
    dataHash: string;
    timestamp: bigint;
    registeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FIRVerifiedEvent {
  export type InputTuple = [
    firId: string,
    verifiedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    firId: string,
    verifiedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    firId: string;
    verifiedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FIRRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FIRRegistry;
  waitForDeployment(): Promise<this>;

  interface: FIRRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  firCount: TypedContractMethod<[], [bigint], "view">;

  getFIR: TypedContractMethod<
    [firId: string],
    [
      [string, string, string, bigint, string] & {
        firId_: string;
        cid_: string;
        dataHash_: string;
        timestamp_: bigint;
        registeredBy_: string;
      }
    ],
    "view"
  >;

  getVerification: TypedContractMethod<
    [firId: string],
    [
      [string, bigint, boolean] & {
        verifiedBy_: string;
        timestamp_: bigint;
        exists_: boolean;
      }
    ],
    "view"
  >;

  isFIRRegistered: TypedContractMethod<[firId: string], [boolean], "view">;

  registerFIR: TypedContractMethod<
    [firId: string, cid: string, dataHash: string],
    [void],
    "nonpayable"
  >;

  verifyFIR: TypedContractMethod<[firId: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "firCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFIR"
  ): TypedContractMethod<
    [firId: string],
    [
      [string, string, string, bigint, string] & {
        firId_: string;
        cid_: string;
        dataHash_: string;
        timestamp_: bigint;
        registeredBy_: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerification"
  ): TypedContractMethod<
    [firId: string],
    [
      [string, bigint, boolean] & {
        verifiedBy_: string;
        timestamp_: bigint;
        exists_: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFIRRegistered"
  ): TypedContractMethod<[firId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerFIR"
  ): TypedContractMethod<
    [firId: string, cid: string, dataHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyFIR"
  ): TypedContractMethod<[firId: string], [void], "nonpayable">;

  getEvent(
    key: "FIRCreated"
  ): TypedContractEvent<
    FIRCreatedEvent.InputTuple,
    FIRCreatedEvent.OutputTuple,
    FIRCreatedEvent.OutputObject
  >;
  getEvent(
    key: "FIRVerified"
  ): TypedContractEvent<
    FIRVerifiedEvent.InputTuple,
    FIRVerifiedEvent.OutputTuple,
    FIRVerifiedEvent.OutputObject
  >;

  filters: {
    "FIRCreated(string,string,string,uint256,address)": TypedContractEvent<
      FIRCreatedEvent.InputTuple,
      FIRCreatedEvent.OutputTuple,
      FIRCreatedEvent.OutputObject
    >;
    FIRCreated: TypedContractEvent<
      FIRCreatedEvent.InputTuple,
      FIRCreatedEvent.OutputTuple,
      FIRCreatedEvent.OutputObject
    >;

    "FIRVerified(string,address,uint256)": TypedContractEvent<
      FIRVerifiedEvent.InputTuple,
      FIRVerifiedEvent.OutputTuple,
      FIRVerifiedEvent.OutputObject
    >;
    FIRVerified: TypedContractEvent<
      FIRVerifiedEvent.InputTuple,
      FIRVerifiedEvent.OutputTuple,
      FIRVerifiedEvent.OutputObject
    >;
  };
}
