/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FIRRegistry } from "./FIRRegistry";
export * as factories from "./factories";
export { FIRRegistry__factory } from "./factories/FIRRegistry__factory";
